load("@rules_java//java:defs.bzl", "java_binary")

# These rules are not meant to be run directly, but as a means to get a single
# jar file containing all of e2e test dependencies. There are conflicts with
# tradefed jar dependencies: e2e_tests_pre comes first in the classpath while
# e2e_tests_post comes last.
java_binary(
    name = "e2e_tests_pre",
    testonly = 1,
    use_launcher = False,
    visibility = ["//ets:__pkg__"],
    runtime_deps = [
        "//ets/java/com/android/tools/e2etests/netsim:netsim_daemon_test",
    ],
)

java_binary(
    name = "e2e_tests_post",
    testonly = 1,
    resource_strip_prefix = "ets/java/com/android/tools/e2etests",
    resources = glob(["config/*.xml"]),
    use_launcher = False,
    visibility = ["//ets:__pkg__"],
    runtime_deps = [
        "//ets/java/com/android/tools/e2etests/avd:avd_test",
        "//ets/java/com/android/tools/e2etests/discovery:display_name_test",
        "//ets/java/com/android/tools/e2etests/display:adb_screen_cap_test",
        "//ets/java/com/android/tools/e2etests/events:close_emulator_test",
        "//ets/java/com/android/tools/e2etests/files:adb_push_pull_test",
        "//ets/java/com/android/tools/e2etests/netsim:netsim_daemon_test",
        "//ets/java/com/android/tools/e2etests/netsim:netsim_single_device_test",
        "//ets/java/com/android/tools/e2etests/snapshot:snapshot_test",
        "//ets/java/com/android/tools/e2etests/telnet:telnet_test",
        "//ets/java/com/android/tools/e2etests/vulkan:vulkan_app_test",
        "//testlib/java/com/android/tools/testlib/tradefed:emulator_test_suite",
        "//testlib/java/com/android/tools/testlib/tradefed:log_saver",
        "//testlib/java/com/android/tools/testlib/tradefed:xml_reporter",
    ],
)
