load("//ets:ets.bzl", "ets_host_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [":adb_push_pull_test_config"],
)

ets_host_test(
    name = "adb_push_pull_test",
    srcs = ["AdbPushPullTest.kt"],
    class_name = "com.android.tools.e2etests.files.AdbPushPullTest",
    description = "Host tests checking adb push and pull",
    deps = [
        "@tradefed//:tradefed_jars",
    ],
)
