# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import emulator_controller_pb2 as emulator__controller__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class EmulatorControllerStub(object):
  """An EmulatorController service lets you control the emulator.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.setRotation = channel.unary_unary(
        '/android.emulation.control.EmulatorController/setRotation',
        request_serializer=emulator__controller__pb2.Rotation.SerializeToString,
        response_deserializer=emulator__controller__pb2.Rotation.FromString,
        )
    self.getRotation = channel.unary_unary(
        '/android.emulation.control.EmulatorController/getRotation',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=emulator__controller__pb2.Rotation.FromString,
        )
    self.setBattery = channel.unary_unary(
        '/android.emulation.control.EmulatorController/setBattery',
        request_serializer=emulator__controller__pb2.BatteryState.SerializeToString,
        response_deserializer=emulator__controller__pb2.BatteryState.FromString,
        )
    self.getBattery = channel.unary_unary(
        '/android.emulation.control.EmulatorController/getBattery',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=emulator__controller__pb2.BatteryState.FromString,
        )
    self.getGps = channel.unary_unary(
        '/android.emulation.control.EmulatorController/getGps',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=emulator__controller__pb2.GpsState.FromString,
        )
    self.setGps = channel.unary_unary(
        '/android.emulation.control.EmulatorController/setGps',
        request_serializer=emulator__controller__pb2.GpsState.SerializeToString,
        response_deserializer=emulator__controller__pb2.GpsState.FromString,
        )
    self.sendFingerprint = channel.unary_unary(
        '/android.emulation.control.EmulatorController/sendFingerprint',
        request_serializer=emulator__controller__pb2.FingerprintEvent.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.sendKey = channel.unary_unary(
        '/android.emulation.control.EmulatorController/sendKey',
        request_serializer=emulator__controller__pb2.KeyboardEvent.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.sendTouch = channel.unary_unary(
        '/android.emulation.control.EmulatorController/sendTouch',
        request_serializer=emulator__controller__pb2.TouchEvent.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.sendMouse = channel.unary_unary(
        '/android.emulation.control.EmulatorController/sendMouse',
        request_serializer=emulator__controller__pb2.MouseEvent.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.sendRotary = channel.unary_unary(
        '/android.emulation.control.EmulatorController/sendRotary',
        request_serializer=emulator__controller__pb2.RotaryEvent.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.getStatus = channel.unary_unary(
        '/android.emulation.control.EmulatorController/getStatus',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=emulator__controller__pb2.EmulatorStatus.FromString,
        )
    self.getScreenshot = channel.unary_unary(
        '/android.emulation.control.EmulatorController/getScreenshot',
        request_serializer=emulator__controller__pb2.ImageFormat.SerializeToString,
        response_deserializer=emulator__controller__pb2.Image.FromString,
        )
    self.getLogcat = channel.unary_unary(
        '/android.emulation.control.EmulatorController/getLogcat',
        request_serializer=emulator__controller__pb2.LogMessage.SerializeToString,
        response_deserializer=emulator__controller__pb2.LogMessage.FromString,
        )
    self.streamLogcat = channel.unary_stream(
        '/android.emulation.control.EmulatorController/streamLogcat',
        request_serializer=emulator__controller__pb2.LogMessage.SerializeToString,
        response_deserializer=emulator__controller__pb2.LogMessage.FromString,
        )
    self.usePhone = channel.unary_unary(
        '/android.emulation.control.EmulatorController/usePhone',
        request_serializer=emulator__controller__pb2.TelephoneOperation.SerializeToString,
        response_deserializer=emulator__controller__pb2.TelephoneResponse.FromString,
        )
    self.requestRtcStream = channel.unary_unary(
        '/android.emulation.control.EmulatorController/requestRtcStream',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=emulator__controller__pb2.RtcId.FromString,
        )
    self.sendJsepMessage = channel.unary_unary(
        '/android.emulation.control.EmulatorController/sendJsepMessage',
        request_serializer=emulator__controller__pb2.JsepMsg.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.receiveJsepMessage = channel.unary_unary(
        '/android.emulation.control.EmulatorController/receiveJsepMessage',
        request_serializer=emulator__controller__pb2.RtcId.SerializeToString,
        response_deserializer=emulator__controller__pb2.JsepMsg.FromString,
        )


class EmulatorControllerServicer(object):
  """An EmulatorController service lets you control the emulator.
  """

  def setRotation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getRotation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setBattery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getBattery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getGps(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setGps(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendFingerprint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendTouch(self, request, context):
    """Note that touch events can be used instead of mouse events if desired.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendMouse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendRotary(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getScreenshot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getLogcat(self, request, context):
    """Returns the last 128Kb of logcat output from the emulator
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def streamLogcat(self, request, context):
    """Streams the logcat output from the emulator. The first call
    can retrieve up to 128Kb. This call will not return.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def usePhone(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def requestRtcStream(self, request, context):
    """The following endpoints are needed to establish the webrtc protocol
    Due to limitiations in Javascript we cannot make use of bidirectional
    endpoints See this [blog](https://grpc.io/blog/state-of-grpc-web) for
    details.

    This function will generate a new identifier that the client
    should use for further interaction. It will initiate the
    JSEP protocol on the server side.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendJsepMessage(self, request, context):
    """Sends the given JsepMsg to the server. The RtcId in the
    message should point to an active stream negotiation in
    progress, otherwise the message will be ignored.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def receiveJsepMessage(self, request, context):
    """Reads an available jsep messages for the given client id,
    blocking at most 5 seconds, or until one becomes available.

    The ice candidates for example will trickle in on this callback,
    as will the SDP negotation.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EmulatorControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'setRotation': grpc.unary_unary_rpc_method_handler(
          servicer.setRotation,
          request_deserializer=emulator__controller__pb2.Rotation.FromString,
          response_serializer=emulator__controller__pb2.Rotation.SerializeToString,
      ),
      'getRotation': grpc.unary_unary_rpc_method_handler(
          servicer.getRotation,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=emulator__controller__pb2.Rotation.SerializeToString,
      ),
      'setBattery': grpc.unary_unary_rpc_method_handler(
          servicer.setBattery,
          request_deserializer=emulator__controller__pb2.BatteryState.FromString,
          response_serializer=emulator__controller__pb2.BatteryState.SerializeToString,
      ),
      'getBattery': grpc.unary_unary_rpc_method_handler(
          servicer.getBattery,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=emulator__controller__pb2.BatteryState.SerializeToString,
      ),
      'getGps': grpc.unary_unary_rpc_method_handler(
          servicer.getGps,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=emulator__controller__pb2.GpsState.SerializeToString,
      ),
      'setGps': grpc.unary_unary_rpc_method_handler(
          servicer.setGps,
          request_deserializer=emulator__controller__pb2.GpsState.FromString,
          response_serializer=emulator__controller__pb2.GpsState.SerializeToString,
      ),
      'sendFingerprint': grpc.unary_unary_rpc_method_handler(
          servicer.sendFingerprint,
          request_deserializer=emulator__controller__pb2.FingerprintEvent.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'sendKey': grpc.unary_unary_rpc_method_handler(
          servicer.sendKey,
          request_deserializer=emulator__controller__pb2.KeyboardEvent.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'sendTouch': grpc.unary_unary_rpc_method_handler(
          servicer.sendTouch,
          request_deserializer=emulator__controller__pb2.TouchEvent.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'sendMouse': grpc.unary_unary_rpc_method_handler(
          servicer.sendMouse,
          request_deserializer=emulator__controller__pb2.MouseEvent.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'sendRotary': grpc.unary_unary_rpc_method_handler(
          servicer.sendRotary,
          request_deserializer=emulator__controller__pb2.RotaryEvent.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'getStatus': grpc.unary_unary_rpc_method_handler(
          servicer.getStatus,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=emulator__controller__pb2.EmulatorStatus.SerializeToString,
      ),
      'getScreenshot': grpc.unary_unary_rpc_method_handler(
          servicer.getScreenshot,
          request_deserializer=emulator__controller__pb2.ImageFormat.FromString,
          response_serializer=emulator__controller__pb2.Image.SerializeToString,
      ),
      'getLogcat': grpc.unary_unary_rpc_method_handler(
          servicer.getLogcat,
          request_deserializer=emulator__controller__pb2.LogMessage.FromString,
          response_serializer=emulator__controller__pb2.LogMessage.SerializeToString,
      ),
      'streamLogcat': grpc.unary_stream_rpc_method_handler(
          servicer.streamLogcat,
          request_deserializer=emulator__controller__pb2.LogMessage.FromString,
          response_serializer=emulator__controller__pb2.LogMessage.SerializeToString,
      ),
      'usePhone': grpc.unary_unary_rpc_method_handler(
          servicer.usePhone,
          request_deserializer=emulator__controller__pb2.TelephoneOperation.FromString,
          response_serializer=emulator__controller__pb2.TelephoneResponse.SerializeToString,
      ),
      'requestRtcStream': grpc.unary_unary_rpc_method_handler(
          servicer.requestRtcStream,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=emulator__controller__pb2.RtcId.SerializeToString,
      ),
      'sendJsepMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendJsepMessage,
          request_deserializer=emulator__controller__pb2.JsepMsg.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'receiveJsepMessage': grpc.unary_unary_rpc_method_handler(
          servicer.receiveJsepMessage,
          request_deserializer=emulator__controller__pb2.RtcId.FromString,
          response_serializer=emulator__controller__pb2.JsepMsg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'android.emulation.control.EmulatorController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
