# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import snapshot_service_pb2 as snapshot__service__pb2


class SnapshotServiceStub(object):
  """The SnapshotService enables you to list, store, and retrieve snapshots.
  Currently the snapshot service is very limited, in the sense that you can:

  1. Store only one snapshot. All existing snapshots will be deleted.
  2. Cannot rename the snapshots.
  3. There are no guarantees that you will be able to load the snapshot
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.listSnapshots = channel.unary_unary(
        '/android.emulation.control.SnapshotService/listSnapshots',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=snapshot__service__pb2.SnapshotList.FromString,
        )
    self.pullSnapshot = channel.unary_stream(
        '/android.emulation.control.SnapshotService/pullSnapshot',
        request_serializer=snapshot__service__pb2.Snapshot.SerializeToString,
        response_deserializer=snapshot__service__pb2.Snapshot.FromString,
        )
    self.pushSnapshot = channel.stream_unary(
        '/android.emulation.control.SnapshotService/pushSnapshot',
        request_serializer=snapshot__service__pb2.Snapshot.SerializeToString,
        response_deserializer=snapshot__service__pb2.Snapshot.FromString,
        )
    self.loadSnapshot = channel.unary_unary(
        '/android.emulation.control.SnapshotService/loadSnapshot',
        request_serializer=snapshot__service__pb2.Snapshot.SerializeToString,
        response_deserializer=snapshot__service__pb2.Snapshot.FromString,
        )
    self.saveSnapshot = channel.unary_unary(
        '/android.emulation.control.SnapshotService/saveSnapshot',
        request_serializer=snapshot__service__pb2.Snapshot.SerializeToString,
        response_deserializer=snapshot__service__pb2.Snapshot.FromString,
        )
    self.deleteSnapshot = channel.unary_unary(
        '/android.emulation.control.SnapshotService/deleteSnapshot',
        request_serializer=snapshot__service__pb2.Snapshot.SerializeToString,
        response_deserializer=snapshot__service__pb2.Snapshot.FromString,
        )


class SnapshotServiceServicer(object):
  """The SnapshotService enables you to list, store, and retrieve snapshots.
  Currently the snapshot service is very limited, in the sense that you can:

  1. Store only one snapshot. All existing snapshots will be deleted.
  2. Cannot rename the snapshots.
  3. There are no guarantees that you will be able to load the snapshot
  """

  def listSnapshots(self, request, context):
    """Lists all the valid snapshots that are stored locally for the currently
    running avd.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def pullSnapshot(self, request, context):
    """Pulls down the snapshot stored inside the AVD as a tar.gz stream
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def pushSnapshot(self, request_iterator, context):
    """Push a tar.gz stream contain the snapshot.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def loadSnapshot(self, request, context):
    """Loads the given snapshot inside the emulator.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def saveSnapshot(self, request, context):
    """Create as a snapshot of the current state of the emulator.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteSnapshot(self, request, context):
    """Deletes the given snapshot from the avd.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SnapshotServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'listSnapshots': grpc.unary_unary_rpc_method_handler(
          servicer.listSnapshots,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=snapshot__service__pb2.SnapshotList.SerializeToString,
      ),
      'pullSnapshot': grpc.unary_stream_rpc_method_handler(
          servicer.pullSnapshot,
          request_deserializer=snapshot__service__pb2.Snapshot.FromString,
          response_serializer=snapshot__service__pb2.Snapshot.SerializeToString,
      ),
      'pushSnapshot': grpc.stream_unary_rpc_method_handler(
          servicer.pushSnapshot,
          request_deserializer=snapshot__service__pb2.Snapshot.FromString,
          response_serializer=snapshot__service__pb2.Snapshot.SerializeToString,
      ),
      'loadSnapshot': grpc.unary_unary_rpc_method_handler(
          servicer.loadSnapshot,
          request_deserializer=snapshot__service__pb2.Snapshot.FromString,
          response_serializer=snapshot__service__pb2.Snapshot.SerializeToString,
      ),
      'saveSnapshot': grpc.unary_unary_rpc_method_handler(
          servicer.saveSnapshot,
          request_deserializer=snapshot__service__pb2.Snapshot.FromString,
          response_serializer=snapshot__service__pb2.Snapshot.SerializeToString,
      ),
      'deleteSnapshot': grpc.unary_unary_rpc_method_handler(
          servicer.deleteSnapshot,
          request_deserializer=snapshot__service__pb2.Snapshot.FromString,
          response_serializer=snapshot__service__pb2.Snapshot.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'android.emulation.control.SnapshotService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
