# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshot_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import snapshot_pb2 as snapshot__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='snapshot_service.proto',
  package='android.emulation.control',
  syntax='proto3',
  serialized_options=b'\n\034com.android.emulator.controlP\001\242\002\003AEC',
  serialized_pb=b'\n\x16snapshot_service.proto\x12\x19\x61ndroid.emulation.control\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0esnapshot.proto\"\xb6\x01\n\x0fSnapshotPackage\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0b\n\x03\x65rr\x18\x04 \x01(\x0c\x12\x41\n\x06\x66ormat\x18\x05 \x01(\x0e\x32\x31.android.emulation.control.SnapshotPackage.Format\"\x1c\n\x06\x46ormat\x12\t\n\x05TARGZ\x10\x00\x12\x07\n\x03TAR\x10\x01\"T\n\x0fSnapshotDetails\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12,\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32\x1b.emulator_snapshot.Snapshot\"M\n\x0cSnapshotList\x12=\n\tsnapshots\x18\x01 \x03(\x0b\x32*.android.emulation.control.SnapshotDetails\"c\n\x0cIceboxTarget\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12\x14\n\x0cpackage_name\x18\x02 \x01(\t\x12\x13\n\x0bsnapshot_id\x18\x03 \x01(\t\x12\x0e\n\x06\x66\x61iled\x18\x04 \x01(\x08\x12\x0b\n\x03\x65rr\x18\x05 \x01(\t2\xe1\x05\n\x0fSnapshotService\x12R\n\rListSnapshots\x12\x16.google.protobuf.Empty\x1a\'.android.emulation.control.SnapshotList\"\x00\x12j\n\x0cPullSnapshot\x12*.android.emulation.control.SnapshotPackage\x1a*.android.emulation.control.SnapshotPackage\"\x00\x30\x01\x12j\n\x0cPushSnapshot\x12*.android.emulation.control.SnapshotPackage\x1a*.android.emulation.control.SnapshotPackage\"\x00(\x01\x12h\n\x0cLoadSnapshot\x12*.android.emulation.control.SnapshotPackage\x1a*.android.emulation.control.SnapshotPackage\"\x00\x12h\n\x0cSaveSnapshot\x12*.android.emulation.control.SnapshotPackage\x1a*.android.emulation.control.SnapshotPackage\"\x00\x12j\n\x0e\x44\x65leteSnapshot\x12*.android.emulation.control.SnapshotPackage\x1a*.android.emulation.control.SnapshotPackage\"\x00\x12\x62\n\x0cTrackProcess\x12\'.android.emulation.control.IceboxTarget\x1a\'.android.emulation.control.IceboxTarget\"\x00\x42&\n\x1c\x63om.android.emulator.controlP\x01\xa2\x02\x03\x41\x45\x43\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,snapshot__pb2.DESCRIPTOR,])



_SNAPSHOTPACKAGE_FORMAT = _descriptor.EnumDescriptor(
  name='Format',
  full_name='android.emulation.control.SnapshotPackage.Format',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TARGZ', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=253,
  serialized_end=281,
)
_sym_db.RegisterEnumDescriptor(_SNAPSHOTPACKAGE_FORMAT)


_SNAPSHOTPACKAGE = _descriptor.Descriptor(
  name='SnapshotPackage',
  full_name='android.emulation.control.SnapshotPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='android.emulation.control.SnapshotPackage.snapshot_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='android.emulation.control.SnapshotPackage.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='android.emulation.control.SnapshotPackage.success', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='android.emulation.control.SnapshotPackage.err', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='android.emulation.control.SnapshotPackage.format', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SNAPSHOTPACKAGE_FORMAT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=281,
)


_SNAPSHOTDETAILS = _descriptor.Descriptor(
  name='SnapshotDetails',
  full_name='android.emulation.control.SnapshotDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='android.emulation.control.SnapshotDetails.snapshot_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='android.emulation.control.SnapshotDetails.details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=367,
)


_SNAPSHOTLIST = _descriptor.Descriptor(
  name='SnapshotList',
  full_name='android.emulation.control.SnapshotList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshots', full_name='android.emulation.control.SnapshotList.snapshots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=446,
)


_ICEBOXTARGET = _descriptor.Descriptor(
  name='IceboxTarget',
  full_name='android.emulation.control.IceboxTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='android.emulation.control.IceboxTarget.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_name', full_name='android.emulation.control.IceboxTarget.package_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='android.emulation.control.IceboxTarget.snapshot_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failed', full_name='android.emulation.control.IceboxTarget.failed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='android.emulation.control.IceboxTarget.err', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=547,
)

_SNAPSHOTPACKAGE.fields_by_name['format'].enum_type = _SNAPSHOTPACKAGE_FORMAT
_SNAPSHOTPACKAGE_FORMAT.containing_type = _SNAPSHOTPACKAGE
_SNAPSHOTDETAILS.fields_by_name['details'].message_type = snapshot__pb2._SNAPSHOT
_SNAPSHOTLIST.fields_by_name['snapshots'].message_type = _SNAPSHOTDETAILS
DESCRIPTOR.message_types_by_name['SnapshotPackage'] = _SNAPSHOTPACKAGE
DESCRIPTOR.message_types_by_name['SnapshotDetails'] = _SNAPSHOTDETAILS
DESCRIPTOR.message_types_by_name['SnapshotList'] = _SNAPSHOTLIST
DESCRIPTOR.message_types_by_name['IceboxTarget'] = _ICEBOXTARGET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SnapshotPackage = _reflection.GeneratedProtocolMessageType('SnapshotPackage', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTPACKAGE,
  '__module__' : 'snapshot_service_pb2'
  # @@protoc_insertion_point(class_scope:android.emulation.control.SnapshotPackage)
  })
_sym_db.RegisterMessage(SnapshotPackage)

SnapshotDetails = _reflection.GeneratedProtocolMessageType('SnapshotDetails', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTDETAILS,
  '__module__' : 'snapshot_service_pb2'
  # @@protoc_insertion_point(class_scope:android.emulation.control.SnapshotDetails)
  })
_sym_db.RegisterMessage(SnapshotDetails)

SnapshotList = _reflection.GeneratedProtocolMessageType('SnapshotList', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTLIST,
  '__module__' : 'snapshot_service_pb2'
  # @@protoc_insertion_point(class_scope:android.emulation.control.SnapshotList)
  })
_sym_db.RegisterMessage(SnapshotList)

IceboxTarget = _reflection.GeneratedProtocolMessageType('IceboxTarget', (_message.Message,), {
  'DESCRIPTOR' : _ICEBOXTARGET,
  '__module__' : 'snapshot_service_pb2'
  # @@protoc_insertion_point(class_scope:android.emulation.control.IceboxTarget)
  })
_sym_db.RegisterMessage(IceboxTarget)


DESCRIPTOR._options = None

_SNAPSHOTSERVICE = _descriptor.ServiceDescriptor(
  name='SnapshotService',
  full_name='android.emulation.control.SnapshotService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=550,
  serialized_end=1287,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListSnapshots',
    full_name='android.emulation.control.SnapshotService.ListSnapshots',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SNAPSHOTLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PullSnapshot',
    full_name='android.emulation.control.SnapshotService.PullSnapshot',
    index=1,
    containing_service=None,
    input_type=_SNAPSHOTPACKAGE,
    output_type=_SNAPSHOTPACKAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PushSnapshot',
    full_name='android.emulation.control.SnapshotService.PushSnapshot',
    index=2,
    containing_service=None,
    input_type=_SNAPSHOTPACKAGE,
    output_type=_SNAPSHOTPACKAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoadSnapshot',
    full_name='android.emulation.control.SnapshotService.LoadSnapshot',
    index=3,
    containing_service=None,
    input_type=_SNAPSHOTPACKAGE,
    output_type=_SNAPSHOTPACKAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SaveSnapshot',
    full_name='android.emulation.control.SnapshotService.SaveSnapshot',
    index=4,
    containing_service=None,
    input_type=_SNAPSHOTPACKAGE,
    output_type=_SNAPSHOTPACKAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteSnapshot',
    full_name='android.emulation.control.SnapshotService.DeleteSnapshot',
    index=5,
    containing_service=None,
    input_type=_SNAPSHOTPACKAGE,
    output_type=_SNAPSHOTPACKAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TrackProcess',
    full_name='android.emulation.control.SnapshotService.TrackProcess',
    index=6,
    containing_service=None,
    input_type=_ICEBOXTARGET,
    output_type=_ICEBOXTARGET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SNAPSHOTSERVICE)

DESCRIPTOR.services_by_name['SnapshotService'] = _SNAPSHOTSERVICE

# @@protoc_insertion_point(module_scope)
