# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshot-service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import snapshot_pb2 as snapshot__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='snapshot-service.proto',
  package='android.emulation.control',
  syntax='proto3',
  serialized_options=_b('\n\024com.android.emulatorP\001\242\002\003AEC'),
  serialized_pb=_b('\n\x16snapshot-service.proto\x12\x19\x61ndroid.emulation.control\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0esnapshot.proto\"\xa8\x01\n\x08Snapshot\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0b\n\x03\x65rr\x18\x04 \x01(\x0c\x12:\n\x06\x66ormat\x18\x05 \x01(\x0e\x32*.android.emulation.control.Snapshot.Format\"\x1c\n\x06\x46ormat\x12\t\n\x05TARGZ\x10\x00\x12\x07\n\x03TAR\x10\x01\"T\n\x0fSnapshotDetails\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12,\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32\x1b.emulator_snapshot.Snapshot\"M\n\x0cSnapshotList\x12=\n\tsnapshots\x18\x01 \x03(\x0b\x32*.android.emulation.control.SnapshotDetails2\xb7\x04\n\x0fSnapshotService\x12R\n\rlistSnapshots\x12\x16.google.protobuf.Empty\x1a\'.android.emulation.control.SnapshotList\"\x00\x12\\\n\x0cpullSnapshot\x12#.android.emulation.control.Snapshot\x1a#.android.emulation.control.Snapshot\"\x00\x30\x01\x12\\\n\x0cpushSnapshot\x12#.android.emulation.control.Snapshot\x1a#.android.emulation.control.Snapshot\"\x00(\x01\x12Z\n\x0cloadSnapshot\x12#.android.emulation.control.Snapshot\x1a#.android.emulation.control.Snapshot\"\x00\x12Z\n\x0csaveSnapshot\x12#.android.emulation.control.Snapshot\x1a#.android.emulation.control.Snapshot\"\x00\x12\\\n\x0e\x64\x65leteSnapshot\x12#.android.emulation.control.Snapshot\x1a#.android.emulation.control.Snapshot\"\x00\x42\x1e\n\x14\x63om.android.emulatorP\x01\xa2\x02\x03\x41\x45\x43\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,snapshot__pb2.DESCRIPTOR,])



_SNAPSHOT_FORMAT = _descriptor.EnumDescriptor(
  name='Format',
  full_name='android.emulation.control.SnapshotPackage.Format',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TARGZ', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=239,
  serialized_end=267,
)
_sym_db.RegisterEnumDescriptor(_SNAPSHOT_FORMAT)


_SNAPSHOT = _descriptor.Descriptor(
  name='Snapshot',
  full_name='android.emulation.control.SnapshotPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='android.emulation.control.SnapshotPackage.snapshot_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='android.emulation.control.SnapshotPackage.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='android.emulation.control.SnapshotPackage.success', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='android.emulation.control.SnapshotPackage.err', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='android.emulation.control.SnapshotPackage.format', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SNAPSHOT_FORMAT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=267,
)


_SNAPSHOTDETAILS = _descriptor.Descriptor(
  name='SnapshotDetails',
  full_name='android.emulation.control.SnapshotDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='android.emulation.control.SnapshotDetails.snapshot_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='android.emulation.control.SnapshotDetails.details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=353,
)


_SNAPSHOTLIST = _descriptor.Descriptor(
  name='SnapshotList',
  full_name='android.emulation.control.SnapshotList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshots', full_name='android.emulation.control.SnapshotList.snapshots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=432,
)

_SNAPSHOT.fields_by_name['format'].enum_type = _SNAPSHOT_FORMAT
_SNAPSHOT_FORMAT.containing_type = _SNAPSHOT
_SNAPSHOTDETAILS.fields_by_name['details'].message_type = snapshot__pb2._SNAPSHOT
_SNAPSHOTLIST.fields_by_name['snapshots'].message_type = _SNAPSHOTDETAILS
DESCRIPTOR.message_types_by_name['Snapshot'] = _SNAPSHOT
DESCRIPTOR.message_types_by_name['SnapshotDetails'] = _SNAPSHOTDETAILS
DESCRIPTOR.message_types_by_name['SnapshotList'] = _SNAPSHOTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Snapshot = _reflection.GeneratedProtocolMessageType('SnapshotPackage', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOT,
  '__module__' : 'snapshot_service_pb2'
  # @@protoc_insertion_point(class_scope:android.emulation.control.Snapshot)
  })
_sym_db.RegisterMessage(Snapshot)

SnapshotDetails = _reflection.GeneratedProtocolMessageType('SnapshotDetails', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTDETAILS,
  '__module__' : 'snapshot_service_pb2'
  # @@protoc_insertion_point(class_scope:android.emulation.control.SnapshotDetails)
  })
_sym_db.RegisterMessage(SnapshotDetails)

SnapshotList = _reflection.GeneratedProtocolMessageType('SnapshotList', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTLIST,
  '__module__' : 'snapshot_service_pb2'
  # @@protoc_insertion_point(class_scope:android.emulation.control.SnapshotList)
  })
_sym_db.RegisterMessage(SnapshotList)


DESCRIPTOR._options = None

_SNAPSHOTSERVICE = _descriptor.ServiceDescriptor(
  name='SnapshotService',
  full_name='android.emulation.control.SnapshotService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=435,
  serialized_end=1002,
  methods=[
  _descriptor.MethodDescriptor(
    name='listSnapshots',
    full_name='android.emulation.control.SnapshotService.listSnapshots',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SNAPSHOTLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='pullSnapshot',
    full_name='android.emulation.control.SnapshotService.pullSnapshot',
    index=1,
    containing_service=None,
    input_type=_SNAPSHOT,
    output_type=_SNAPSHOT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='pushSnapshot',
    full_name='android.emulation.control.SnapshotService.pushSnapshot',
    index=2,
    containing_service=None,
    input_type=_SNAPSHOT,
    output_type=_SNAPSHOT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='loadSnapshot',
    full_name='android.emulation.control.SnapshotService.loadSnapshot',
    index=3,
    containing_service=None,
    input_type=_SNAPSHOT,
    output_type=_SNAPSHOT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='saveSnapshot',
    full_name='android.emulation.control.SnapshotService.saveSnapshot',
    index=4,
    containing_service=None,
    input_type=_SNAPSHOT,
    output_type=_SNAPSHOT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteSnapshot',
    full_name='android.emulation.control.SnapshotService.deleteSnapshot',
    index=5,
    containing_service=None,
    input_type=_SNAPSHOT,
    output_type=_SNAPSHOT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SNAPSHOTSERVICE)

DESCRIPTOR.services_by_name['SnapshotService'] = _SNAPSHOTSERVICE

# @@protoc_insertion_point(module_scope)
