# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import waterfall_pb2 as waterfall__pb2


class WaterfallStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.stream_stream(
        '/waterfall.Waterfall/Echo',
        request_serializer=waterfall__pb2.Message.SerializeToString,
        response_deserializer=waterfall__pb2.Message.FromString,
        )
    self.Push = channel.stream_unary(
        '/waterfall.Waterfall/Push',
        request_serializer=waterfall__pb2.Transfer.SerializeToString,
        response_deserializer=waterfall__pb2.Transfer.FromString,
        )
    self.Pull = channel.unary_stream(
        '/waterfall.Waterfall/Pull',
        request_serializer=waterfall__pb2.Transfer.SerializeToString,
        response_deserializer=waterfall__pb2.Transfer.FromString,
        )
    self.Exec = channel.stream_stream(
        '/waterfall.Waterfall/Exec',
        request_serializer=waterfall__pb2.CmdProgress.SerializeToString,
        response_deserializer=waterfall__pb2.CmdProgress.FromString,
        )
    self.Forward = channel.stream_stream(
        '/waterfall.Waterfall/Forward',
        request_serializer=waterfall__pb2.ForwardMessage.SerializeToString,
        response_deserializer=waterfall__pb2.ForwardMessage.FromString,
        )
    self.Version = channel.unary_unary(
        '/waterfall.Waterfall/Version',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=waterfall__pb2.VersionMessage.FromString,
        )


class WaterfallServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Echo(self, request_iterator, context):
    """Echo exists solely for test purposes.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Push(self, request_iterator, context):
    """Push file/dir from host to device.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Pull(self, request, context):
    """Pull file/dir from device to host.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Exec(self, request_iterator, context):
    """Exec executes cmd in the device and foward stdout and stderr to client
    Exec expects a single initial CmdProgress message if stdin is not
    being redirected. Otherwise Exec will read std from the stream.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Forward(self, request_iterator, context):
    """Forward forwards the stream payload to the requested socket
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Version(self, request, context):
    """Version gets the version of the server.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WaterfallServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.stream_stream_rpc_method_handler(
          servicer.Echo,
          request_deserializer=waterfall__pb2.Message.FromString,
          response_serializer=waterfall__pb2.Message.SerializeToString,
      ),
      'Push': grpc.stream_unary_rpc_method_handler(
          servicer.Push,
          request_deserializer=waterfall__pb2.Transfer.FromString,
          response_serializer=waterfall__pb2.Transfer.SerializeToString,
      ),
      'Pull': grpc.unary_stream_rpc_method_handler(
          servicer.Pull,
          request_deserializer=waterfall__pb2.Transfer.FromString,
          response_serializer=waterfall__pb2.Transfer.SerializeToString,
      ),
      'Exec': grpc.stream_stream_rpc_method_handler(
          servicer.Exec,
          request_deserializer=waterfall__pb2.CmdProgress.FromString,
          response_serializer=waterfall__pb2.CmdProgress.SerializeToString,
      ),
      'Forward': grpc.stream_stream_rpc_method_handler(
          servicer.Forward,
          request_deserializer=waterfall__pb2.ForwardMessage.FromString,
          response_serializer=waterfall__pb2.ForwardMessage.SerializeToString,
      ),
      'Version': grpc.unary_unary_rpc_method_handler(
          servicer.Version,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=waterfall__pb2.VersionMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'waterfall.Waterfall', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PortForwarderStub(object):
  """PortForwarder service runs a port forwarding session via waterfall.
  It allows start and stop forwarding connections when the waterfall client
  is unable to mantains any state (e.g. the waterfall adb binary).
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ForwardPort = channel.unary_unary(
        '/waterfall.PortForwarder/ForwardPort',
        request_serializer=waterfall__pb2.PortForwardRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Stop = channel.unary_unary(
        '/waterfall.PortForwarder/Stop',
        request_serializer=waterfall__pb2.PortForwardRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.StopAll = channel.unary_unary(
        '/waterfall.PortForwarder/StopAll',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.List = channel.unary_unary(
        '/waterfall.PortForwarder/List',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=waterfall__pb2.ForwardedSessions.FromString,
        )


class PortForwarderServicer(object):
  """PortForwarder service runs a port forwarding session via waterfall.
  It allows start and stop forwarding connections when the waterfall client
  is unable to mantains any state (e.g. the waterfall adb binary).
  """

  def ForwardPort(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Stop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PortForwarderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ForwardPort': grpc.unary_unary_rpc_method_handler(
          servicer.ForwardPort,
          request_deserializer=waterfall__pb2.PortForwardRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Stop': grpc.unary_unary_rpc_method_handler(
          servicer.Stop,
          request_deserializer=waterfall__pb2.PortForwardRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'StopAll': grpc.unary_unary_rpc_method_handler(
          servicer.StopAll,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=waterfall__pb2.ForwardedSessions.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'waterfall.PortForwarder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
