[pytest]
norecursedirs = docs *.egg-info .git src js venv py2 py.tox
log_format = %(asctime)s.%(msecs)03d %(name)-12s %(levelname)-7s %(message)s
log_date_format = %H:%M:%S
log_level = DEBUG
log_file_level = DEBUG
log_file_format = %(asctime)s.%(msecs)03d %(name)-12s %(levelname)-7s %(message)s
log_auto_indent = True
junit_logging = log
default_async_timeout = 60

# The number of times we want to retry if we detect a crash, if the emulator
# crashes we will run the test at most 3 times.
crash_retries = 2

# Enable log cli if you want to see logs as you go (lots of logging!)
# log_cli = True

# Our timeout mechanism is not officially supported in pytest 8, but works
# fine, see https://github.com/pytest-dev/pytest/issues/12850
filterwarnings =
    ignore::pytest.PytestRemovedIn9Warning

## addopts = --strict-markers
# Various test markers, generally you can would want to exclude lower priority
# tests when running higher priority tests.
markers =
    e2e: ** DEPRECATED ** An end 2 end test
    sanity: Emulator sanity tests. These are P0 tests, and should always succeed.
    fast: Emulator fast suite tests. These are P1 tests, and should always succeed.
    netsim: Verifies netsim functionality
    standard: Tests independent of an emulator
    adb: Exercises adb functionality
    android_tv: Runs on Android TV
    boot: Validates behavior immediately after boot
    oldapiboot: Validates behavior immediately after boot for older apis
    console: Relates to the emulator console
    embedded: Runs only on an embedded emulator
    foldable: Operates on a foldable emulator
    newfoldable: Uses new foldable emulator API since 34
    graphics: Relates to graphics operations
    hardware: Low-level hardware test
    hostperf: Host-side performance test
    guestperf: Guest-side performance test
    resizable: Runs on a resizable emulator
    newresizable: Uses new resizable emulator API since 34
    embedded_newresizable: Uses new resizable emulator API since 34, in embedded mode
    snapshot: Relates to snapshot operations
    multidisplay: Relates to multi-display
    windows: Runs only on Windows
    chrome: Chrome tests
    netsim: Netsim emulator tests
    wear: Runs on Wear OS
    multi: Uses multiple emulator at the same time.
    std: Standard test that does not need an emulator
    tablet: Runs on a tablet image
    atv: Runs on an android tv image
    embedded_new_resizable: New resizable embedded emulator API since 34
    wifi_perf: WiFi performance test
    uiautomator: Performs UI actions

testpaths =
    tests

