[pytest]
norecursedirs = docs *.egg-info .git src js venv py2 py.tox
# Our fixtures are very expensive (i.e. booting emulator)
# and we do not want a timeout marker to include a possible emulator boot.
timeout_func_only = true
log_format = %(asctime)s %(thread)d %(name)-30s %(levelname)-7s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_level = INFO
log_file_level = INFO
log_file_format = %(asctime)s %(thread)d %(name)-12s %(basename)s:%(lineno)d %(levelname)s %(message)s
log_auto_indent = True

junit_logging = log

# Enable log cli if you want to see logs as you go (lots of logging!)
log_cli = False
markers =
    adb: marks test as adb test.
    boot: marks tests as boot test, these tests validate that something hold just after booting. (deselect with '-m "not boot"')
    console: mark tests related to the emulator console
    darwin: marks test as darwin only, will only run if you are on darwin.
    e2e: marks test as end to end (deselect with '-m "not e2e"')
    embedded: marks test as embedded only, will run on an embedded emulator.
    foldable: marks test that operates on a foldable emulator
    graphics: marks tests related to graphics operations
    hardware: marks test as a low-level hardware test
    linux: marks test as linux only, will only run if you are on linux.
    perf: marks test as a performance test (deselect with '-m "not perf"')
    resizable: marks test that should run on a resizable emulator
    slow: marks tests as slow (deselect with '-m "not slow"')
    snapshot: marks tests related to snapshot operations
    multidisplay: mark tests related to multidisplay
    win32: marks test as windows only, will only run on a windows machine.
testpaths =
    tests

