load("@rules_android//rules:rules.bzl", "android_binary")
load("@rules_kotlin//kotlin:android.bzl", "kt_android_library")

filegroup(
    name = "pkg",
    testonly = 1,
    srcs = [
        ":ClockTest.apk",
        ":ClockTest.config",
    ],
    visibility = ["//xts:__pkg__"],
)

kt_android_library(
    name = "clock_lib",
    testonly = 1,
    srcs = ["ClockTest.kt"],
    deps = [
        "//testlib/java/com/android/tools/testlib/verifier:cts_verifier",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_runner",
        "@maven//:androidx_test_services_storage",
        "@maven//:androidx_test_uiautomator_uiautomator",
        "@tradefed//:tradefed_jars",
    ],
)

android_binary(
    name = "ClockTest",
    testonly = 1,
    custom_package = "com.android.tools.e2etests.lock",
    manifest = "ClockTestManifest.xml",
    manifest_values = {
        "minSdkVersion": "36",
        "targetSdkVersion": "36",
    },
    deps = [":clock_lib"],
)

