load("@rules_java//java:defs.bzl", "java_binary")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "display_name_test",
    srcs = ["DisplayNameTest.kt"],
    deps = [
        "//testlib/java/com/android/tools/testlib/emu:discovery",
        "@tradefed//:tradefed_jars",
    ],
)

# This rule is not meant to be run directly, but as a means to get a single jar file containing all
# of e2e test dependencies.
java_binary(
    name = "e2e_tests",
    testonly = 1,
    use_launcher = False,
    visibility = ["//tests/ets:__pkg__"],
    runtime_deps = [
        ":display_name_test",
        "//testlib/java/com/android/tools/testlib/tradefed:log_saver",
        "//testlib/java/com/android/tools/testlib/tradefed:xml_reporter",
    ],
)
