load("//ets:ets.bzl", "ets_host_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [
        ":netsim_daemon_test_config",
        ":netsim_single_device_test_config",
    ],
)

ets_host_test(
    name = "netsim_daemon_test",
    srcs = ["NetsimDaemonTest.kt"],
    class_name = "com.android.tools.e2etests.netsim.NetsimDaemonTest",
    description = "Host tests for the netsim daemon",
    deps = [
        "//testlib/java/com/android/tools/testlib/netsim:netsimd",
        "@maven//:com_github_oshi_oshi_core",
        "@maven//:junit_junit",
        "@maven//:net_java_dev_jna_jna",
        "@maven//:net_java_dev_jna_jna_platform",
        "@tradefed//:tradefed_jars",
    ],
)

ets_host_test(
    name = "netsim_single_device_test",
    srcs = ["NetsimSingleDeviceTest.kt"],
    class_name = "com.android.tools.e2etests.netsim.NetsimSingleDeviceTest",
    description = "Host tests for netsim using a single device",
    deps = [
        "//testlib/java/com/android/tools/testlib/netsim:grpc",
        "@netsim//proto:netsim_java_grpc",
        "@netsim//proto:netsim_java_proto",
        "@tradefed//:tradefed_jars",
    ],
)
