load("//ets:ets.bzl", "ets_device_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [
        ":InputTest.apk",
        ":InputTest_config",
    ],
)

ets_device_test(
    name = "InputTest",
    srcs = [
        "AndroidInputTest.kt",
        "EvDevConstants.kt",
        "EventObserver.kt",
        "InputTestActivity.kt",
        "KeyboardInputTest.kt",
        "MouseInputTest.kt",
        "PenInputTest.kt",
        "TouchInputTest.kt",
        "TouchpadInputTest.kt",
        "WheelInputTest.kt",
    ],
    description = "Tests related to the emulator Input",
    manifest_app_extra = """
       <activity android:name=".InputTestActivity" android:exported="true">
           <intent-filter>
               <action android:name="android.intent.action.MAIN"/>
               <category android:name="android.intent.category.LAUNCHER"/>
           </intent-filter>
       </activity>
    """,
    package = "com.android.tools.e2etests.input",
    deps = [
        "//deps/proto:aemu_java_grpc_lite",
        "//ets/java/com/android/tools/e2etests/grpc:grpc_lib",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_runner",
        "@maven//:androidx_test_uiautomator_uiautomator",
        "@tradefed//:tradefed_jars",
    ],
)

