load("//ets:ets.bzl", "ets_device_test", "ets_host_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [
        ":ScreenshotTest.apk",
        ":ScreenshotTest_config",
        ":adb_screen_cap_test_config",
    ],
)

ets_host_test(
    name = "adb_screen_cap_test",
    srcs = ["AdbScreenCapTest.kt"],
    class_name = "com.android.tools.e2etests.display.AdbScreenCapTest",
    description = "Host test checking adb screencap",
    deps = [
        "@tradefed//:tradefed_jars",
    ],
)

ets_device_test(
    name = "ScreenshotTest",
    srcs = ["ScreenshotTest.kt"],
    description = "Tests related to the emulator screenshots",
    extra_apks = ["app-debug.apk"],
    manifest_extra = """
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
    <queries>
        <package android:name="com.google.AnimateBox" />
    </queries>
    """,
    package = "com.android.tools.e2etests.display",
    pull_files = True,
    deps = [
        "//deps/proto:aemu_java_grpc_lite",
        "//ets/java/com/android/tools/e2etests/animatebox:animate_box",
        "//ets/java/com/android/tools/e2etests/grpc:grpc_lib",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_runner",
        "@maven//:androidx_test_services_storage",
        "@maven//:androidx_test_uiautomator_uiautomator",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@tradefed//:tradefed_jars",
    ],
)
