load("//ets:ets.bzl", "ets_host_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [":telnet_test_config"],
)

ets_host_test(
    name = "telnet_test",
    srcs = ["TelnetTest.kt"],
    class_name = "com.android.tools.e2etests.telnet.TelnetTest",
    description = "Host test which checks the telnet interface",
    deps = [
        "//testlib/java/com/android/tools/testlib/emu:discovery",
        "//testlib/java/com/android/tools/testlib/emu:telnet",
        "@maven//:junit_junit",
        "@tradefed//:tradefed_jars",
    ],
)
