load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "discovery_test",
    size = "small",
    srcs = ["DiscoveryTest.kt"],
    test_class = "com.android.tools.testlib.emu.DiscoveryTest",
    deps = [
        "//testlib/java/com/android/tools/testlib/emu:discovery",
        "@bazel_tools//tools/jdk:TestRunner",
    ],
)

kt_jvm_test(
    name = "eventually_test",
    size = "small",
    srcs = ["EventuallyTest.kt"],
    test_class = "com.android.tools.testlib.emu.EventuallyTest",
    deps = [
        "//testlib/java/com/android/tools/testlib/emu:eventually",
        "@bazel_tools//tools/jdk:TestRunner",
    ],
)
