load("@rules_android//rules:rules.bzl", "android_binary")
load("@rules_kotlin//kotlin:android.bzl", "kt_android_library")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

filegroup(
    name = "pkg",
    testonly = 1,
    srcs = glob(["*.config"]) + [":ControlKeysTest.apk"],
    visibility = ["//ets:__pkg__"],
)

kt_jvm_test(
    name = "close_emulator_test",
    srcs = ["CloseEmulatorTest.kt"],
    visibility = ["//ets/java/com/android/tools/e2etests:__pkg__"],
    deps = [
        "//deps/proto:aemu_java_grpc",
        "//deps/proto:aemu_java_proto",
        "//testlib/java/com/android/tools/testlib/emu:discovery",
        "//testlib/java/com/android/tools/testlib/netsim:netsimd",
        "@grpc-java//api",
        "@grpc-java//context",
        "@grpc-java//protobuf",
        "@grpc-java//stub",
        "@maven//:com_github_oshi_oshi_core",
        "@maven//:junit_junit",
        "@maven//:net_java_dev_jna_jna",
        "@maven//:net_java_dev_jna_jna_platform",
        "@protobuf//:protobuf_java",
        "@protobuf//:protobuf_java_util",
        "@tradefed//:tradefed_jars",
    ],
)

kt_android_library(
    name = "control_keys_test_lib",
    testonly = 1,
    srcs = ["ControlKeysTest.kt"],
    deps = [
        "//deps/proto:aemu_java_grpc",
        "//deps/proto:aemu_java_proto",
        "//ets/java/com/android/tools/e2etests/grpc:grpc_lib",
        "//testlib/java/com/android/tools/testlib/emu:adb",
        "//testlib/java/com/android/tools/testlib/emu:eventually",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_runner",
        "@tradefed//:tradefed_jars",
    ],
)

android_binary(
    name = "ControlKeysTest",
    testonly = 1,
    custom_package = "com.android.tools.e2etests.events",
    manifest = "ControlKeysTestManifest.xml",
    manifest_values = {
        "minSdkVersion": "36",
        "targetSdkVersion": "36",
    },
    deps = [":control_keys_test_lib"],
)
