load("@rules_kotlin//kotlin:android.bzl", "kt_android_library")

kt_android_library(
    name = "animate_box",
    testonly = 1,
    srcs = ["AnimateBox.kt"],
    visibility = ["//ets/java/com/android/tools/e2etests:__subpackages__"],
    deps = [
        "//testlib/java/com/android/tools/testlib/emu:adb",
        "//testlib/java/com/android/tools/testlib/emu:eventually",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_uiautomator_uiautomator",
    ],
)
