load("//ets:ets.bzl", "ets_device_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [
        ":BatteryTest.apk",
        ":BatteryTest_config",
    ],
)

ets_device_test(
    name = "BatteryTest",
    srcs = ["BatteryTest.kt"],
    description = "Test which checks the battery",
    package = "com.android.tools.e2etests.battery",
    deps = [
        "//deps/proto:aemu_java_grpc_lite",
        "//ets/java/com/android/tools/e2etests/grpc:grpc_lib",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_runner",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
    ],
)
