#!/usr/bin/env python3
"""
Auto-generated pass test script for CtsVerifier test: Device Admin Tapjacking Test
Generated by automation_dev/test_builder.py
"""

import os
import sys
import time

sys.stdout.reconfigure(line_buffering=True)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(SCRIPT_DIR)

from cts_common import (
    adb,
    setup,
    navigate_to,
    ui_dump,
    find_node,
    tap,
    tap_pass,
    screenshot,
    set_screenshot_dir,
    export_and_verify,
    reboot_and_wait,
    wait_for,
    wait_for_screen_off,
    wait_for_keyguard_showing,
)

TEST_NAME = "Device Admin Tapjacking Test"

set_screenshot_dir("device_admin_tapjacking_test")

# Step 0: Setup & Launch
setup()
screenshot("app_launched")

# Step 1: Navigate to Test
navigate_to(TEST_NAME)
time.sleep(2)
screenshot("test_opened")

# Step 2: Recorded Test Actions
# Wait for and tap "OK"

node = wait_for(text="OK", timeout=15)
tap(node)

# Wait for and tap "Enable device admin"

node = wait_for(text="Enable device admin", timeout=15)
tap(node)
time.sleep(3)

# Key event 4

adb("shell", "input", "keyevent", "4")
time.sleep(2)

# Key event 4

adb("shell", "input", "keyevent", "4")
time.sleep(2)

# Wait for and tap Pass button

pass_btn = wait_for(content_desc="Pass", timeout=15)
tap_pass(pass_btn)
time.sleep(2)

# Export test result

adb("shell", "am", "start", "-n", "com.android.cts.verifier/.CtsVerifierActivity")
time.sleep(3)
export_and_verify(TEST_NAME)

print(f"Finished Device Admin Tapjacking Test successfully!")
