# Copyright 2020 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""A basic emulator launcher."""
import logging
import os
import re
import subprocess
import shutil
import tempfile
from emu.template_writer import TemplateWriter


class AvdGenerator(object):
    """A generator for a default avd.

    AVDs are generated by creating a Pixel2 based virtual devices, in a temporary
    directory that is removed when this object goes out of scope.
    """

    IMAGE = re.compile(
        r".*android-(\d+)[\/\\](default|google_apis|google_apis_playstore|android-tv)[\/\\](x86|x86_64)[\/\\]system.img$"
    )

    def __init__(self, sdk_root, avd_home):
        self.sdk_root = sdk_root
        self.sys_root = os.path.abspath(os.path.join(sdk_root, "system-images"))
        if os.path.exists(avd_home):
            self.avd_home = avd_home
        else:
            self.tmpdir = tempfile.mkdtemp("avd")
            self.avd_home = tmpdir
        self.writer = TemplateWriter(self.avd_home)

    def __del__(self):
        if self.tmpdir:
            shutil.rmtree(self.tmpdir)

    def _find_images(self):
        for x in self._recursive_iglob(self.sys_root, [self.IMAGE.match]):
            m = self.IMAGE.match(x)
            logging.debug("Found %s", x)
            yield {
                "api": m.group(1),
                "tag": m.group(2),
                "abi": m.group(3),
                "cpu": m.group(3),
                "image_dir": os.path.join(
                    "system-images",
                    "android-{}".format(m.group(1)),
                    m.group(2),
                    m.group(3),
                ),
                "avd_dir": os.path.join(self.avd_home, "Pixel2.avd"),
            }

    def _find_avd(self, api, abi, tag):
        return [
            x
            for x in self._find_images()
            if x["api"] == api and x["abi"] == abi and x["tag"] == tag
        ]

    def _install_sys_image(self, api, abi, tag="google_apis"):
        logging.info("Installing system-images;android-{};{};{}".format(api, tag, abi))
        subprocess.check_output(
            [
                os.path.join(self.sdk_root, "tools", "bin", "sdkmanager"),
                "system-images;android-{};{};{}".format(api, tag, abi),
            ]
        )

    def _create_avd(self, api, abi, tag):
        avds = self._find_avd(api, abi, tag)
        if not avds:
            self._install_sys_image(api, abi, tag)
            avds = self._find_avd(api, abi, tag)
        avd = avds[0]

        self.writer.write_template("Pixel2.ini", avd)
        self.writer.write_template("Pixel2.avd/config.ini", avd)

    def get_avd(self, api, abi, tag):
        """Returns the AVD name, creating it if needed."""
        if not os.path.exists(os.path.join(self.avd_home, "Pixel2.ini")):
            self._create_avd(api, abi, tag)

        return "Pixel2"

    def get_avd_home(self):
        """Returns the ANDROID_AVD_HOME, creating the avd if needed"""
        if not os.path.exists(os.path.join(self.avd_home, "Pixel2.ini")):
            self._create_avd()

        return self.avd_home

    def _recursive_iglob(self, rootdir, pattern_fns):
        """Recursively glob the rootdir for any file that matches the pattern functions."""
        for root, _, filenames in os.walk(rootdir):
            for filename in filenames:
                fname = os.path.join(root, filename)
                for pattern_fn in pattern_fns:
                    if pattern_fn(fname):
                        yield fname
