load("//ets:ets.bzl", "ets_host_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [":avd_test_config"],
)

ets_host_test(
    name = "avd_test",
    srcs = ["AvdTest.kt"],
    class_name = "com.android.tools.e2etests.avd.AvdTest",
    description = "Host test which checks the AVD",
    deps = [
        "//deps/proto:aemu_java_grpc",
        "//deps/proto:aemu_java_proto",
        "//ets/java/com/android/tools/e2etests/grpc:host_grpc_lib",
        "//testlib/java/com/android/tools/testlib/emu:discovery",
        "@grpc-java//api",
        "@grpc-java//context",
        "@grpc-java//protobuf",
        "@grpc-java//stub",
        "@maven//:junit_junit",
        "@protobuf//:protobuf_java",
        "@protobuf//:protobuf_java_util",
        "@tradefed//:tradefed_jars",
    ],
)
