PlayStore.enabled={{playstore}}
avd.ini.displayname=31
avd.ini.encoding=UTF-8
disk.dataPartition.size=32M
fastboot.chosenSnapshotFile=
fastboot.forceChosenSnapshotBoot=no
fastboot.forceColdBoot=no
fastboot.forceFastBoot=yes
hw.accelerometer=yes
hw.arc=false
hw.audioInput=yes
hw.battery=yes
hw.camera.back=virtualscene
hw.camera.front=emulated
hw.cpu.arch={{host_cpu}}
hw.cpu.ncore=4
hw.dPad=no
hw.device.hash2=MD5:3274126e0242a0d86339850416b0ce34
hw.device.manufacturer=Google
hw.device.name=pixel_5
hw.gps=yes
hw.gpu.enabled=yes
hw.gpu.mode=auto
hw.initialOrientation=Portrait
hw.keyboard=yes
hw.lcd.density=440
hw.lcd.height=2340
hw.lcd.width=1080
hw.mainKeys=no
hw.ramSize=1536
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
# image.sysdir.1=
runtime.network.latency=none
runtime.network.speed=full
sdcard.size=16M
showDeviceFrame=yes
skin.dynamic=yes
tag.display=Google APIs
# tag.id=google_apis
# Unused, these come from a dictionary that is passed in
# tag.id={{tag}}
# AvdId=31
# abi.type={{abi}}
# hw.cpu.arch={{cpu}}
image.sysdir.1={{image_dir}}

