load("@rules_android//rules:rules.bzl", "android_binary")
load("@rules_kotlin//kotlin:android.bzl", "kt_android_library")

filegroup(
    name = "pkg",
    testonly = 1,
    srcs = [
        ":CtsVerifierTest.apk",
        ":CtsVerifierTest.config",
    ],
    visibility = ["//ets:__pkg__"],
)

kt_android_library(
    name = "cts_verifier_lib",
    testonly = 1,
    srcs = ["CtsVerifierTest.kt"],
    deps = [
        "//deps/proto:aemu_java_grpc_lite",
        "//ets/java/com/android/tools/e2etests/grpc:grpc_lib",
        "//testlib/java/com/android/tools/testlib/emu:adb",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_runner",
        "@maven//:androidx_test_services_storage",
        "@maven//:androidx_test_uiautomator_uiautomator",
        "@tradefed//:tradefed_jars",
    ],
)

android_binary(
    name = "CtsVerifierTest",
    testonly = 1,
    custom_package = "com.android.tools.e2etests.ctsverifier",
    manifest = "CtsVerifierTestManifest.xml",
    manifest_values = {
        "minSdkVersion": "36",
        "targetSdkVersion": "36",
    },
    deps = [":cts_verifier_lib"],
)
