PlayStore.enabled={{playstore}}
avd.ini.encoding=UTF-8
disk.dataPartition.size=8G
fastboot.chosenSnapshotFile=
fastboot.forceChosenSnapshotBoot=no
fastboot.forceColdBoot=no
fastboot.forceFastBoot=yes
hw.accelerometer=yes
hw.audioInput=yes
hw.battery=yes
hw.camera.back=virtualscene
hw.camera.front=emulated
hw.cpu.arch={{host_cpu}}
hw.cpu.ncore=4
hw.dPad=no
hw.device.hash2=MD5:253a4eaf19dee95e9be9194ced30b3df
hw.device.manufacturer=Google
hw.device.name=pixel_fold
hw.displayRegion.0.1.height=2092
hw.displayRegion.0.1.width=1080
hw.displayRegion.0.1.xOffset=0
hw.displayRegion.0.1.yOffset=0
hw.gps=yes
hw.gpu.enabled=yes
hw.gpu.mode=auto
hw.initialOrientation=Portrait
hw.keyboard=yes
hw.lcd.density=420
hw.lcd.height=1840
hw.lcd.width=2208
hw.mainKeys=no
hw.ramSize=2048
hw.sdCard=yes
hw.sensor.hinge=yes
hw.sensor.hinge.areas=1080-0-0-1840
hw.sensor.hinge.count=1
hw.sensor.hinge.defaults=180
hw.sensor.hinge.ranges=0-180
hw.sensor.hinge.sub_type=1
hw.sensor.hinge.type=1
hw.sensor.hinge_angles_posture_definitions=0-30, 30-150, 150-180
hw.sensor.posture_list=1, 2, 3
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
# image.sysdir.1=
runtime.network.latency=none
runtime.network.speed=full
sdcard.size=512M
showDeviceFrame=yes
skin.dynamic=yes
skin.name=2208x1840
skin.path=_no_skin
skin.path.backup=_no_skin
tag.display=Google APIs
# tag.id=google_apis
# Unused, these come from a dictionary that is passed in
# tag.id={{tag}}
# AvdId=31
# abi.type={{abi}}
# hw.cpu.arch={{cpu}}
image.sysdir.1={{image_dir}}
