load("@rules_android//rules:rules.bzl", "android_binary")
load("@rules_kotlin//kotlin:android.bzl", "kt_android_library")

filegroup(
    name = "pkg",
    testonly = 1,
    srcs = [
        ":ConnectivityTest.config",
        ":ConnectivityTest.apk",
    ],
    visibility = ["//ets:__pkg__"],
)

kt_android_library(
    name = "connectivity_test_lib",
    testonly = 1,
    srcs = ["ConnectivityTest.kt"],
    deps = [
        "//testlib/java/com/android/tools/testlib/emu:adb",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_runner",
        "@maven//:androidx_test_uiautomator_uiautomator",
    ],
)

android_binary(
    name = "ConnectivityTest",
    testonly = 1,
    custom_package = "com.android.tools.e2etests.wifi",
    manifest = "ConnectivityTestManifest.xml",
    manifest_values = {
        "minSdkVersion": "36",
        "targetSdkVersion": "36",
    },
    deps = [":connectivity_test_lib"],
)

