load("//ets:ets.bzl", "ets_device_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [
        ":ConnectivityTest_config",
        ":ConnectivityTest.apk",
    ],
)

ets_device_test(
    name = "ConnectivityTest",
    srcs = ["ConnectivityTest.kt"],
    description = "Tests related to the emulator wifi connectivity",
    package = "com.android.tools.e2etests.wifi",
    deps = [
        "//testlib/java/com/android/tools/testlib/emu:adb",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_runner",
        "@maven//:androidx_test_uiautomator_uiautomator",
    ],
)
