"""
Auto-generate CLs in Gerrit for API 19 and above.

1, Moves apks into android git from go/gmscore-apks.
2, Bump sdk images version.
3, Update prebuilt_constants if necessary.

"""
import collections
import errno
import glob
import os
import re
import shutil
import tempfile
import zipfile
import subprocess
from absl import app
from absl import flags
from absl import logging
import git_change_utils

FLAGS = flags.FLAGS
flags.DEFINE_string('api_level', None, 'Android SDK API level')
flags.DEFINE_string('x20_base', '/google/data/ro/teams/gmscore/gmscore_apks', (
    'x20 directory to pull from e.x. /google/data/ro/teams/gmscore/'
    'gmscore_apks.'))
flags.DEFINE_string('rapid_candidate_id', None,
                    'Id for release candidate that consists of'
                    '{branch_name/rc_name}. e.x. gmscore_v9/gmscore_v9_RC27')
flags.DEFINE_string('x20_candidate_dir', None,
                    'Directory where candidate apks are relative to x20_base.'
                    'e.x. releases/v9/gmscore_v9_RC27')
flags.DEFINE_string('version_code', None, 'Version of apk to push. e.x. 8.8.66')
flags.DEFINE_string(
    'bug', None,
    'Tracking bug for this platform drops of this gmscore and platform version')
flags.DEFINE_string('branch', None,
                    'Branch of Gerrit project to submit change to')
flags.DEFINE_string('git', 'git', 'Path to git binary from '
                    'devtools/gerritcodereview/git-remote-google MPM')
flags.DEFINE_enum(
    'releaseable_to', None, ['none', 'preview', 'public'],
    'An enum that indicates where these binarys can be released to.')

flags.DEFINE_boolean('dry_run', False, 'Only generate CL but not uploading to Gerrit server')

RAPID_URL = 'http://rapid/#/candidate/gmscore_prod/{}'
APK_COMMIT_MESSAGE = """Import {rapid_candidate} build v{version_code}

Stored here: http://go/gmscore-apks/{x20_candidate_dir}

This build IS suitable for public release.

Bug: {bug}
"""

BUMP_VERSION_COMMIT_MESSAGE = """atv-sdk: bump revision for GmsCore update

Bug: {bug}
"""

CONSTANTS_COMMIT_MESSAGE = """
Update constants/config for GmsCore {rapid_candidate} build v{version_code}

Bug: {bug}
""" [1:]

MK_CONSTANTS_HEADER = """# This file was generated by
# devrel/gmscore/release/push/platform_drop.py. Please do not
# update it by hand unless a gmscore version is being deleted from the
# prebuilts.  If that is the case then it is ok to delete the corresponding
# constants.

"""

MK_CONSTANTS_NAME = 'prebuilt_constants.mk'

METADATA_STRING = """package: name='{}'
versionCode='{}'
versionName='{}'
platformBuildVersionName='{}'
compileSdkVersion='{}'
compileSdkVersionCodename='{}'
sdkVersion:'{}'
targetSdkVersion:'{}'
"""

ARCH_TO_DIR = {
    'armv7': 'arm',
    'arm64': 'arm64',
    'x86': 'x86',
    'x86_64': 'x86_64'
}

PROD_ARCH_TO_DIR = {
    'armv7': 'armeabi-v7a',
    'arm64': 'arm64-v8a',
    'x86': 'x86',
    'x86_64': 'x86_64'
}

BUILD_TYPE_TO_REPO = {
    'prodmnc': 'mnc',
    'atv': 'pano',
    'prodlmp' : 'lmp',
}

BUILD_TYPE_TO_MK_MODULE = {
    'atv': 'pano',
    'prodmnc': 'common',
}

API_LEVEL_AND_BRANCH_NAME = [
    ('19', 'klp-emu-dev'),
    ('21', 'lmp-emu-dev'),
    ('22', 'lmp-mr1-emu-dev'),
    ('23', 'mnc-emu-dev'),
    ('24', 'nyc-emu-dev'),
    ('25','nyc-mr1-emu-dev'),
    ('26', 'oc-emu-dev'),
    ('27', 'oc-mr1-emu-dev'),
    ('28', 'pi-emu-dev')
]

WHAT_TO_DROP_19 = {
    'armv7': {
      'prod': {
          'full': ['alldpi']
      }
    },
    'x86': {
        'prod': {
            'full': ['alldpi'],
        },
    },
}

WHAT_TO_DROP_21_AND_22 = {
    'armv7': {
        'prodlmp': {
            'full': ['alldpi']
        },
    },
    'arm64': {
        'prodlmp': {
            'full': ['alldpi'],
        },
    },
    'x86': {
        'prodlmp': {
            'full': ['alldpi'],
        },
    },
    'x86_64': {
        'prodlmp': {
            'full': ['alldpi'],
        },
    }
}

WHAT_TO_DROP_23_AND_UP = {
    'armv7': {
        'prodmnc': {
            'full': ['alldpi']
        },
    },
    'arm64': {
        'prodmnc': {
            'full': ['alldpi'],
        },
    },
    'x86': {
        'prodmnc': {
            'full': ['alldpi'],
        },
        'atv': {
            'full': ['xhdpi']
        },
    },
    'x86_64': {
        'prodmnc': {
            'full': ['alldpi'],
        },
    }
}


def GmsCorePrebuiltDir(api_level):
  if '19' <= api_level < '24':
    return 'platform/vendor/google'
  else:
    return 'platform/vendor/unbundled_google/packages/GmsCorePrebuilt'  


def GmsCoreVersionDir(api_level):
  if '19' <= api_level < '24':
    return 'prebuilt/GmsCore/v25'
  elif '24' <= api_level < '26':
    return 'v25'
  elif '26' <= api_level < '28':
    return 'v17'
  elif api_level == '28':
    return 'v20'
  else:
    raise ValueError("Unsupported API level: {}".format(api_level))


def SdkImageVersionDirs(api_level):
  if api_level > '25':
    return {'atv' : 'device/google/atv', 'sdk' : 'platform/vendor/google/sdk'}
  elif api_level > '23':
    return {'atv' : 'device/google/atv', 'sdk' : 'platform/vendor/google'}
  else:
    return {'sdk' : 'platform/vendor/google'} 


def MkDir_P(path):
  try:
    os.makedirs(path)
  except OSError as exc:
    if exc.errno == errno.EEXIST and os.path.isdir(path):
      pass
    else:
      raise


def GetOnlyElement(collection):
  if len(collection) == 1:
    return collection[0]
  else:
    raise ValueError('Should find exactly one file. Found: {}'
                     .format(collection))


def _ParseMkConstantsFile(file_path):
  """Parses the constants file and returns a dict of current values."""
  if not os.path.isfile(file_path):
    logging.info('MAKE_FILE Constants file not found: %s', file_path)
    return {}
  constants_dict = {}
  with open(file_path) as constants_file:
    for line in constants_file:
      if ':=' in line:
        key, value = line.split(':=')
        constants_dict[key.strip()] = value.strip()
  return constants_dict


def _WriteConstantsFile(file_path, old_constants, update_constants):
  """Writes the updated constants file."""
  def Sorter(x, y):
    return cmp(x.rsplit('_', 3), y.rsplit('_', 3))

  # shallow copy is safe because both key and value are strings
  new_constants = old_constants.copy()
  new_constants.update(update_constants)
  sorted_constants = sorted(
      new_constants.iteritems(), cmp=Sorter, key=lambda s: s[0])
  contents = MK_CONSTANTS_HEADER + '\n'.join(
      [key + ' := '  + value for key, value in sorted_constants]) + '\n'
  with open(file_path, 'w') as constants_file:
    constants_file.write(contents)


def _GetUpdateMkConstants(file_transfer_infos, gmscore_branch):
  """Creates a dict of constant vars that need to be updated."""
  dynamite_apks = collections.defaultdict(set)
  for file_transfer_info in file_transfer_infos:
    for build_type, module in BUILD_TYPE_TO_MK_MODULE.iteritems():
      if file_transfer_info.build_type == build_type:
        with zipfile.ZipFile(file_transfer_info.source, 'r') as new_apk:
          new_apk_files = new_apk.namelist()

        dynamite_apks[module].update([
            file_path for file_path in new_apk_files
            if file_path.endswith('.apk') and
            'assets/chimera-modules/' in file_path
        ])
  update_dict = {}
  for module in BUILD_TYPE_TO_MK_MODULE.values():
    update_dict[_CreateKey(gmscore_branch, module, '_extracted_apks'
                          )] = _FormatExtractedApks(dynamite_apks[module])

  return update_dict


def _CreateKey(gmscore_branch, module, suffix):
  return (gmscore_branch + '_' + module + suffix).upper()


def _FormatExtractedApks(extracted_apks):
  """Formats extracted dynamite apks into format ingestible by MAKE."""
  # This is required because there can only be unique key entries in the
  # MAKEFILE so we remove duplicates by wildcarding the dpi.
  extracted_apks = list({
      re.sub(r'_[a-zA-Z]+_release.apk', '_%_release.apk', extracted_apk)
      for extracted_apk in extracted_apks
  })
  for i, extracted_apk in enumerate(extracted_apks):
    # Finds name of old-style (<v19) dynamite apk
    # eg. /DynamiteLoader_GmsCore_prodmnc_xhdpi_release.apk -> DynamiteLoader
    match = re.match(r'.+/(\w+)_GmsCore_.+\.apk', extracted_apk)
    if match:
      extracted_apks[i] = match.group(1) + ':' + extracted_apk
    else:
      # Treat this as a new-style (>=v19) dynamite apk, with a simple name
      extracted_apks[i] = '%s:%s' % (
          extracted_apk[extracted_apk.rindex('/') + 1:-4], extracted_apk)

  return ' '.join(sorted(extracted_apks))


# KLP API 19 will not only copy over the apk files. 
# It will also extract .so files for KLP apks and strip .so files in the API for armv7.
def _ApkFileOperationKLP(file_transfer_infos, git_dir, unused_gmscore_branch):
  _ApkFileOperation(file_transfer_infos, git_dir, unused_gmscore_branch)
  for info in file_transfer_infos:
    if "_alldpi_" in info.source:
      parent_dir = os.path.dirname(info.dest)
      subprocess.call(['unzip', '-j', '-o',
        info.dest, 'lib/*', '-d', parent_dir])
      if info.arch == 'armv7':
        subprocess.call(
              ['zip', '-d',
               info.dest, 'lib/*'])
        shutil.move(info.dest, os.path.join(os.path.dirname(parent_dir), os.path.basename(info.dest)))
      else:
        os.remove(info.dest)


def _ApkFileOperation(file_transfer_infos, _, unused_gmscore_branch):
  for file_transfer_info in file_transfer_infos:
    MkDir_P(os.path.dirname(file_transfer_info.dest))
    logging.info("Copy from source {} to dest {}".format(file_transfer_info.source, file_transfer_info.dest))
    shutil.copy(file_transfer_info.source, file_transfer_info.dest)


def _ConstantsFileOperation(file_transfer_infos, git_dir, gmscore_branch):
  constants_file = os.path.join(git_dir, MK_CONSTANTS_NAME)
  _WriteConstantsFile(constants_file,
                      _ParseMkConstantsFile(constants_file),
                      _GetUpdateMkConstants(file_transfer_infos,
                                            gmscore_branch),)

def _RenameApk(build_type, dpi):
  apk_name = 'GmsCore'
  if dpi != 'alldpi':
    apk_name += '-' + dpi
  return apk_name + '-' + BUILD_TYPE_TO_REPO[build_type] + '.apk'


def _RenameApkForKLP(arch):
  if arch == 'x86':
    return 'GmsCore_prod_x86_alldpi_release.apk'
  else:
    return 'GmsCore_prod_armv7_alldpi_release.apk'


def GetApkFileTransferInfo(git_dir,
                           x20_base,
                           x20_candidate_dir,
                           api_level):
  """Gets file paths and drop locations of apks to drop from x20."""
  if api_level == '19':
    what_to_drop = WHAT_TO_DROP_19
  elif api_level == '21' or api_level == '22':
    what_to_drop = WHAT_TO_DROP_21_AND_22
  else:
    what_to_drop = WHAT_TO_DROP_23_AND_UP

  file_transfer_infos = []
  for arch, variants in what_to_drop.iteritems():
    for build_type, apk_type_to_dpis in variants.iteritems():
      for apk_type, dpis in apk_type_to_dpis.iteritems():
        for dpi in dpis:
          if apk_type == 'full':
            if x20_candidate_dir.find('prod/') >= 0:
              if build_type == 'atv':
                file_glob = 'GmsCore_{}_{}_{}_release_signed.apk'.format(
                  build_type, arch, dpi)
              else:
                file_glob = '{}/GmsCore_{}_{}_{}_release.apk'.format(
                  PROD_ARCH_TO_DIR[arch], build_type, arch, dpi)
            else:
              if build_type == 'atv':
                file_glob = 'GmsCore_{}_{}_{}_release_signed-*.apk'.format(
                  build_type, arch, dpi)
              else:
                file_glob = 'GmsCore_{}_{}_{}_release-*.apk'.format(
                  build_type, arch, dpi)
          file_path = os.path.join(x20_base, x20_candidate_dir, file_glob)
          logging.info('Looking for apks of glob: %s', file_path)
          found_file = GetOnlyElement(glob.glob(file_path))
          if api_level == '19':
            apk_name = _RenameApkForKLP(arch)
          else:
            apk_name = _RenameApk(build_type, dpi)

          #For API 26+, the git_dir will be the immediate parent directory of the GmsCore APK. 
          if '19' <= api_level <= '25':
            write_path = os.path.join(git_dir, GmsCoreVersionDir(api_level), ARCH_TO_DIR[arch], apk_name)
          else:
            write_path = os.path.join(git_dir, ARCH_TO_DIR[arch], apk_name)

          file_transfer_infos.append(
              git_change_utils.FileTransferInfo(
                  source=found_file,
                  dest=write_path,
                  arch=arch,
                  build_type=build_type,
                  dpi=dpi))

  return file_transfer_infos


def _CreateTopic(api_level):
  """Creates a topic name for a set of changes on this candidate."""
  return 'GmsCore-update-{0}'.format(api_level)


def _RapidCandidateName(candidate_id):
  """Gets candidate name from candidate id."""
  return candidate_id[candidate_id.find('/') + 1 :]


def _BumpSdkVersion(apk_project, branch_name, base_dir, prop_file_path, topic, commit_message, api_level):
  """Update sdk image version and auto-generate a CL"""
  git_dir = tempfile.mkdtemp('-api-{}-bump-version'.format(api_level), dir=base_dir)
  git_change_utils.CheckoutBranch(FLAGS.git, apk_project, branch_name, git_dir)
  #d = _ParseMkConstantsFile(os.path.join(git_dir, prop_file_path), '=')
  #rev = int(d.get('Pkg.Revision', 0))
  #_WriteConstantsFile(os.path.join(git_dir, prop_file_path), d, {'Pkg.Revision' : str(rev+1)}, '=')
  tmp_file, tmpfile_path = tempfile.mkstemp('prop_file', dir=os.getcwd())
  logging.info(tmpfile_path) 
  with open(os.path.join(git_dir, prop_file_path), 'r') as prop_file:
    for line in prop_file:
      if 'Pkg.Revision' in line:
        key, value = line.split('=')
        value = str(int(value.strip()) + 1)
        key = key.strip()
        os.write(tmp_file, '{}={}\n'.format(key, value))
      else:
        os.write(tmp_file, line)
  os.close(tmp_file)
  shutil.move(tmpfile_path, os.path.join(git_dir, prop_file_path))

  git_change_utils.CreateChange(FLAGS.git, apk_project, branch_name, topic, commit_message,
    None, git_dir, None, None, FLAGS.dry_run)


def run_update(api_level, branch_name, base_dir):

  # create apk push change
  apks_dir = os.path.join(FLAGS.x20_base, FLAGS.x20_candidate_dir)
  if not os.path.isdir(apks_dir):
    raise ValueError('Directory not found: {}'.format(apks_dir))

  apk_git_dir = tempfile.mkdtemp('-api-{}-gmscore-prebuilt-apk'.format(api_level), dir=base_dir)

  candidate_name = _RapidCandidateName(FLAGS.rapid_candidate_id)
  
  topic = _CreateTopic(api_level)
  

  if api_level > '25':
    apk_project = os.path.join(GmsCorePrebuiltDir(api_level), GmsCoreVersionDir(api_level))
  else:
    apk_project = GmsCorePrebuiltDir(api_level)

  logging.info('apk project: ' + apk_project)

  apk_file_transfer_infos = GetApkFileTransferInfo(
      apk_git_dir, FLAGS.x20_base, FLAGS.x20_candidate_dir, api_level)

  # Check out the destination branch now. The old APKs may be used for size
  # diffing, but will eventually be used for the change.
  git_change_utils.CheckoutBranch(FLAGS.git, apk_project, branch_name,
                                  apk_git_dir)

  apk_commit_message = APK_COMMIT_MESSAGE.format(
      rapid_candidate=candidate_name,
      version_code=FLAGS.version_code,
      x20_candidate_dir=FLAGS.x20_candidate_dir,
      bug=FLAGS.bug)

  logging.info('Creating change for GmsCore APKs.')
  git_change_utils.CreateChange(
      FLAGS.git, apk_project, branch_name, topic, apk_commit_message,
      apk_file_transfer_infos, apk_git_dir, GmsCoreVersionDir(api_level),
      _ApkFileOperationKLP if api_level == '19' else _ApkFileOperation, FLAGS.dry_run)

  # bump sdk images version.
  sdk_img_dirs = SdkImageVersionDirs(api_level)

  if 'sdk' in sdk_img_dirs:
    logging.info('Creating change to bump sdk versions.')

    if api_level > '25':
      prop_file_path = 'addons/google_apis/images_source.prop_template'
    else:
      prop_file_path = 'sdk/addons/google_apis/images_source.prop_template'

    _BumpSdkVersion(sdk_img_dirs['sdk'], branch_name, base_dir, prop_file_path,
        topic, BUMP_VERSION_COMMIT_MESSAGE.format(bug=FLAGS.bug), api_level)
    
  if 'atv' in sdk_img_dirs:
    logging.info('Creating change to bump atv versions.')

    _BumpSdkVersion(sdk_img_dirs['atv'], branch_name, os.path.dirname(apk_git_dir), 'sdk/images_x86_source.prop_template',
        topic, BUMP_VERSION_COMMIT_MESSAGE.format(bug=FLAGS.bug), api_level)

  # create constants file change only for API 26+
  if api_level < '26':
    return
  
  constants_git_dir = tempfile.mkdtemp(
      '-api-{}-gmscore-prebuilt-constants'.format(api_level), dir=base_dir)
  apk_project = GmsCorePrebuiltDir(api_level)
  constants_commit_message = CONSTANTS_COMMIT_MESSAGE.format(
      rapid_candidate=FLAGS.rapid_candidate_id,
      version_code=FLAGS.version_code,
      bug=FLAGS.bug)

  logging.info('Creating change for MAKEFILEs.')
  git_change_utils.CheckoutBranch(FLAGS.git, apk_project, branch_name,
                                  constants_git_dir)
  git_change_utils.CreateChange(
      FLAGS.git, apk_project, branch_name, topic, constants_commit_message,
      apk_file_transfer_infos, constants_git_dir, GmsCoreVersionDir(api_level),
      _ConstantsFileOperation, FLAGS.dry_run)

  logging.info('apk git dir: ' + apk_git_dir)
  logging.info('config git dir: ' + constants_git_dir)


def main(unused_argv):
  base_dir = os.getcwd()
  for api, branch_name in API_LEVEL_AND_BRANCH_NAME:
    run_update(api, branch_name, base_dir)


if __name__ == '__main__':
  flags.mark_flag_as_required('bug')
  flags.mark_flag_as_required('rapid_candidate_id')
  flags.mark_flag_as_required('version_code')
  flags.mark_flag_as_required('x20_candidate_dir')
  app.run(main)