load("//ets:ets.bzl", "ets_host_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [":vulkan_app_test_config"],
)

ets_host_test(
    name = "vulkan_app_test",
    srcs = ["VulkanAppTest.kt"],
    class_name = "com.android.tools.e2etests.vulkan.VulkanAppTest",
    description = "Host tests checking vulkan compatibility",
    deps = [
        "@tradefed//:tradefed_jars",
    ],
)
