load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

filegroup(
    name = "pkg",
    testonly = 1,
    srcs = [
        ":VulkanAppTest.config",
    ],
    visibility = ["//ets:__pkg__"],
)

kt_jvm_test(
    name = "vulkan_app_test",
    srcs = ["VulkanAppTest.kt"],
    visibility = ["//ets/java/com/android/tools/e2etests:__pkg__"],
    deps = [
        "@tradefed//:tradefed_jars",
    ],
)
