load("//ets:ets.bzl", "ets_host_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = ["snapshot_test_config"],
)

ets_host_test(
    name = "snapshot_test",
    srcs = ["SnapshotTest.kt"],
    class_name = "com.android.tools.e2etests.snapshot.SnapshotTest",
    description = "Host test which test snapshot functionality",
    deps = [
        "//deps/proto:aemu_java_grpc",
        "//deps/proto:aemu_java_proto",
        "//ets/java/com/android/tools/e2etests/grpc:host_grpc_lib",
        "//testlib/java/com/android/tools/testlib/emu:discovery",
        "@tradefed//:tradefed_jars",
    ],
)
