load("//ets:ets.bzl", "ets_host_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [":display_name_test_config"],
)

ets_host_test(
    name = "display_name_test",
    srcs = ["DisplayNameTest.kt"],
    class_name = "com.android.tools.e2etests.discovery.DisplayNameTest",
    description = "Host test checking the display name",
    deps = [
        "//testlib/java/com/android/tools/testlib/emu:discovery",
        "@tradefed//:tradefed_jars",
    ],
)
