load("@rules_java//java:java_library.bzl", "java_library")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = ["//ets/java/com/android/tools/e2etests:__pkg__"])

java_library(
    name = "emulator_test_suite",
    srcs = ["EmulatorTestSuite.java"],
    deps = [
        "@tradefed//:tradefed_jars",
    ],
)

java_library(
    name = "log_saver",
    srcs = ["XtsFileSystemLogSaver.java"],
    deps = [
        "@tradefed//:tradefed_jars",
    ],
)

kt_jvm_library(
    name = "script_test_runner",
    srcs = ["ScriptTestRunner.kt"],
    visibility = ["//ets/java/com/android/tools/e2etests:__pkg__"],
    deps = [
        "@tradefed//:tradefed_jars",
    ],
)

java_library(
    name = "xml_reporter",
    srcs = ["XtsXmlFormattedGeneratorReporter.java"],
    deps = [
        "@tradefed//:tradefed_jars",
    ],
)
