#!/bin/bash
# This script will extract the memory information from a run of the emulator
# that was launched with the -debug memory flag.
#
# Usually you want to run this on output generated by running the cts tests.
# An example is to run this against the results of a run_local.sh invocation:
#
# ./graph-memory-use.sh -i
# external/adt-infra/emu_test/20170331-03335/CTSTestCase_20170331-033350.log \
#  -o memory_usage.png
#

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
default_in=logfile
default_out=memory_usage.png
option_in=$default_in
option_out=$default_out

if [ $# -eq 0 ]; then
  option_help=yes
fi

while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -h|--help|-\?)
      option_help=yes
      ;;
    -i)
      option_in=${2/#\~/$HOME}
      shift
      ;;
    -o)
      option_out=${2/#\~/$HOME}
      shift
      ;;
    *)
    echo "unknown option '$key', use --help"
    exit 1
    ;;
esac
shift # past argument or value
done


if [ "$option_help" = "yes" ] ; then
    echo "Usage: $0 [options]"
    echo
    echo "Options: [defaults in brackets after descriptions]"
    echo ""
    echo "Standard options:"
    echo "  --help                      Print this message"
    echo "  -i <input>                  Log file containing memory info [$default_in]"
    echo "  -o <output>                 Resulting png image [$default_out]"
    echo
    exit 1
fi

if [ ! -f $option_in ]; then
  echo "file $option_in does not exist"
  exit 1
fi

plotfile=$(mktemp /tmp/plotXXXXXXXX.script)
datafile=$(mktemp /tmp/dataXXXXXXXX)

trap "{  rm -f $plotfile $datafile; }" EXIT

# echo "Gnuplot file: $plotfile"
make_plot() {
echo "set title \"Emulator memory usage over uptime\""  > $1
  cat << EOF >> $1
set term png giant size 1920, 1080
set border 3 front ls 1
# line styles
set style line 1 lc rgb '#1B9E77' # dark teal
set style line 2 lc rgb '#D95F02' # dark orange
set style line 3 lc rgb '#7570B3' # dark lilac
set style line 4 lc rgb '#E7298A' # dark magenta
set style line 5 lc rgb '#66A61E' # dark lime green
set style line 6 lc rgb '#E6AB02' # dark banana
set style line 7 lc rgb '#A6761D' # dark tan
set style line 8 lc rgb '#666666' # dark gray

# palette
set palette maxcolors 8
set palette defined ( 0 '#1B9E77', 1 '#D95F02', 2 '#7570B3', 3 '#E7298A', 4 '#66A61E', 5 '#E6AB02', 6 '#A6761D', 7 '#666666' )
set tics nomirror out scale 0.75
set format '%g'
set ylabel "MAX VSZ"
set ytics nomirror
set yrange[0:*]
set grid
set format y '%.0s%cB' # Note, 1000 bytes = 1 KB
set timefmt "%s"
set xdata time
set format x "%H:%M"
plot "$3" using 1:2 with lines ls 2 lw 2 axes x1y1 title "Res", \
     "$3" using 1:3 with lines ls 3 lw 2 axes x2y1 title "Res Max", \
     "$3" using 1:4 with lines ls 4 lw 2 axes x1y1 title "Virt", \
     "$3" using 1:5 with lines ls 5 lw 2 axes x1y1 title "Virt Max"
EOF
}

# lines always end in something like this MemoryReport: Epoch: 1491000479, Peak: 49874800640
# So we chop of the last columns to get the numbers..

# Get the first data point from the emulator, so we can use that in the title
# first=$(awk '/Epoch: [0-9]+, Peak: [0-9]+$/{print $(NF-2)}' $option_in | sed 's/,$//' | head -1)

# Of course gnuplot doesn't use an epoch that starts in 1970, they start in 2000..
make_plot $plotfile 0 $datafile

# Awk '/Epoch: [0-9]+, Peak: [0-9]+$/{print $(NF-2), $(NF)}' $option_in | gnuplot $plotfile  > $option_out
cat $option_in | grep "MemoryReport" | tr ' ' '\t' | awk '{ print int($4/1000),$6,$7,$8,$9 }' > $datafile

gnuplot $plotfile > $option_out
