load("@rules_pkg//pkg:mappings.bzl", "pkg_attributes", "pkg_filegroup", "pkg_files")
load("@rules_pkg//pkg:zip.bzl", "pkg_zip")
load("//test_seq:test_seq.bzl", "run_sequence")

filegroup(
    name = "ets_plans",
    srcs = ["ets.xml"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "android_ets_templ",
    srcs = ["android_ets.txtpb.templ"],
    visibility = ["//visibility:public"],
)

pkg_files(
    name = "e2e_tests",
    srcs = [
        "ets.xml",
        "//ets/java/com/android/tools/e2etests:e2e_tests_deploy.jar",
    ],
    prefix = "android-ets/tools",
)

pkg_files(
    name = "ets_tradefed",
    srcs = [
        "ets-tradefed",
    ],
    attributes = pkg_attributes(mode = "0777"),
    prefix = "android-ets/tools",
)

pkg_filegroup(
    name = "android_ets",
    srcs = [
        ":e2e_tests",
        ":ets_tradefed",
        "@tradefed//:android_ets",
    ],
)

pkg_zip(
    name = "android_ets_zip",
    srcs = [
        ":android_ets",
    ],
    out = "android-ets.zip",
    visibility = ["//visibility:public"],
)

run_sequence(
    name = "run",
    template = ":android_ets_templ",
    template_args = {
        "goldfish_zip": ("path", "@goldfish//emulator:release"),
        "image_extract_dir": ("dir", "@android_minigbm16k-x86_64//:BUILD.bazel"),
        "platform_tools_extract_dir": ("dir", "@platform-tools-linux//:BUILD.bazel"),
        "build_tools_extract_dir": ("dir", "@build-tools-linux//:BUILD.bazel"),
        "android_ets_zip": ("path", ":android_ets_zip"),
        "ets_plan_xml": ("path", ":ets_plans"),
    },
)
