load("@rules_pkg//pkg:mappings.bzl", "pkg_attributes", "pkg_filegroup", "pkg_files")
load("@rules_pkg//pkg:zip.bzl", "pkg_zip")
load("//test_seq:test_seq.bzl", "run_sequence")

pkg_files(
    name = "e2e_host_tests",
    srcs = [
        "//ets/java/com/android/tools/e2etests:e2e_tests_deploy.jar",
    ],
    prefix = "android-ets/tools",
)

pkg_files(
    name = "ets_modules",
    srcs = [
        "//ets/java/com/android/tools/e2etests:module_configs",
    ],
    prefix = "android-ets/testcases",
)

pkg_files(
    name = "ets_tradefed",
    srcs = [
        "ets-tradefed",
    ],
    attributes = pkg_attributes(mode = "0777"),
    prefix = "android-ets/tools",
)

pkg_filegroup(
    name = "android_ets",
    srcs = [
        ":e2e_host_tests",
        ":ets_modules",
        ":ets_tradefed",
        "@tradefed//:android_ets",
    ],
)

pkg_zip(
    name = "android_ets_zip",
    srcs = [
        ":android_ets",
    ],
    out = "android-ets.zip",
    visibility = ["//visibility:public"],
)

run_sequence(
    name = "run",
    size = "large",
    srcs = ["android_ets_cfg.py"],
    args = [
        "--abi",
        "x86_64",
        "--goldfish_zip",
        "$(location @goldfish//emulator:release)",
        "--image_extract_dir",
        "$(location @android_minigbm16k-x86_64//:BUILD.bazel)",
        "--platform_tools_extract_dir",
        "$(location @platform-tools-linux//:BUILD.bazel)",
        "--build_tools_extract_dir",
        "$(location @build-tools-linux//:BUILD.bazel)",
        "--android_ets_zip",
        "$(location :android_ets_zip)",
    ],
    data = [
        ":android_ets_zip",
        "@android_minigbm16k-x86_64//:BUILD.bazel",
        "@android_minigbm16k-x86_64//:all_files",
        "@build-tools-linux//:BUILD.bazel",
        "@build-tools-linux//:all_files",
        "@goldfish//emulator:release",
        "@platform-tools-linux//:BUILD.bazel",
        "@platform-tools-linux//:all_files",
    ],
    main = "android_ets_cfg.py",
    deps = [
        "//test_seq:config",
    ],
)
