load("@rules_pkg//pkg:mappings.bzl", "pkg_attributes", "pkg_filegroup", "pkg_files")
load("@rules_pkg//pkg:zip.bzl", "pkg_zip")
load("//sequence:sequence.bzl", "run_sequence")

pkg_files(
    name = "e2e_host_tests",
    testonly = True,
    srcs = [
        "//ets/java/com/android/tools/e2etests:e2e_tests_deploy.jar",
    ],
    prefix = "android-ets/tools",
)

pkg_files(
    name = "ets_modules",
    testonly = True,
    srcs = [
        "//ets/java/com/android/tools/e2etests:module_configs",
        "//ets/java/com/android/tools/e2etests/boot:pkg",
        "//ets/java/com/android/tools/e2etests/vulkan:pkg",
    ],
    # Bazel builds the apks in with read-only permissions, which tradefed does
    # not handle.
    attributes = pkg_attributes(mode = "0644"),
    prefix = "android-ets/testcases",
)

pkg_files(
    name = "ets_tradefed",
    testonly = True,
    srcs = [
        "ets-tradefed",
        "ets-tradefed.bat",
    ],
    attributes = pkg_attributes(mode = "0777"),
    prefix = "android-ets/tools",
)

pkg_filegroup(
    name = "android_ets",
    testonly = True,
    srcs = [
        ":e2e_host_tests",
        ":ets_modules",
        ":ets_tradefed",
        "@tradefed//:android_ets",
    ],
)

pkg_zip(
    name = "android_ets_zip",
    testonly = True,
    srcs = [
        ":android_ets",
    ],
    out = "android-ets.zip",
    visibility = ["//visibility:public"],
)

run_sequence(
    name = "run",
    size = "large",
    srcs = ["android_ets_cfg.py"],
    args = [
        "--goldfish_zip",
        "$(rlocationpath @goldfish//emulator:release)",
        "--hellovk_extract_dir",
        "$(rlocationpath @hellovk//:BUILD.bazel)",
        "--tradefed_zip",
        "$(rlocationpath :android_ets_zip)",
        "--emulator_access_json",
        "$(rlocationpath @goldfish//emulator/grpc/security:unsecure-emulator-access)",
    ] + select({
        "@platforms//os:linux": [
            "--abi",
            "x86_64",
            "--build_tools_extract_dir",
            "$(rlocationpath @build-tools-linux//:BUILD.bazel)",
            "--image_extract_dir",
            "$(rlocationpath @android16k-x86_64//:BUILD.bazel)",
            "--platform_tools_extract_dir",
            "$(rlocationpath @platform-tools-linux//:BUILD.bazel)",
        ],
        "@platforms//os:macos": [
            "--abi",
            "arm64",
            "--build_tools_extract_dir",
            "$(rlocationpath @build-tools-mac//:BUILD.bazel)",
            "--image_extract_dir",
            "$(rlocationpath @android16k-arm64-v8a//:BUILD.bazel)",
            "--platform_tools_extract_dir",
            "$(rlocationpath @platform-tools-mac//:BUILD.bazel)",
        ],
    }),
    data = [
        ":android_ets_zip",
        "@goldfish//emulator:release",
        "@goldfish//emulator/grpc/security:unsecure-emulator-access",
        "@hellovk//:BUILD.bazel",
        "@hellovk//:all_files",
    ] + select({
        "@platforms//os:linux": [
            "@android16k-x86_64//:BUILD.bazel",
            "@android16k-x86_64//:all_files",
            "@build-tools-linux//:BUILD.bazel",
            "@build-tools-linux//:all_files",
            "@platform-tools-linux//:BUILD.bazel",
            "@platform-tools-linux//:all_files",
        ],
        "@platforms//os:macos": [
            "@android16k-arm64-v8a//:BUILD.bazel",
            "@android16k-arm64-v8a//:all_files",
            "@build-tools-mac//:BUILD.bazel",
            "@build-tools-mac//:all_files",
            "@platform-tools-mac//:BUILD.bazel",
            "@platform-tools-mac//:all_files",
        ],
    }),
    main = "android_ets_cfg.py",
    tags = [
        "exclusive-if-local",
        "manual",
        "requires-network",
    ],
    deps = [
        "//sequence:agent_common",
        "//sequence:config",
        "@test_seq//test_seq/proto:test_sequencer_pb2",
    ],
)
