load("@rules_pkg//pkg:mappings.bzl", "pkg_attributes", "pkg_filegroup", "pkg_files")
load("@rules_pkg//pkg:zip.bzl", "pkg_zip")

pkg_files(
    name = "e2e_tests",
    srcs = [
        "ets.xml",
        "//tests/ets/java/com/android/tools/e2etests:e2e_tests_deploy.jar",
    ],
    prefix = "android-ets/tools",
)

pkg_files(
    name = "ets_tradefed",
    srcs = [
        "ets-tradefed",
    ],
    attributes = pkg_attributes(mode = "0777"),
    prefix = "android-ets/tools",
)

pkg_filegroup(
    name = "android_ets",
    srcs = [
        ":e2e_tests",
        ":ets_tradefed",
        "@tradefed//:android_ets",
    ],
)

pkg_zip(
    name = "android_ets_zip",
    srcs = [
        ":android_ets",
    ],
    out = "android-ets.zip",
)
