load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "grpc_test",
    size = "small",
    srcs = ["GrpcTest.kt"],
    test_class = "com.android.tools.testlib.netsim.GrpcTest",
    deps = [
        "//testlib/java/com/android/tools/testlib/netsim:grpc",
        "@bazel_tools//tools/jdk:TestRunner",
        "@tradefed//:tradefed_test_jars",
    ],
)

kt_jvm_test(
    name = "netsimd_test",
    size = "small",
    srcs = ["NetsimdTest.kt"],
    test_class = "com.android.tools.testlib.netsim.NetsimdTest",
    deps = [
        "//testlib/java/com/android/tools/testlib/netsim:netsimd",
        "@bazel_tools//tools/jdk:TestRunner",
    ],
)
