load("//ets:ets.bzl", "ets_device_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [
        ":SmsTest.apk",
        ":SmsTest_config",
    ],
)

ets_device_test(
    name = "SmsTest",
    srcs = ["SmsTest.kt"],
    description = "Tests related to the emulator SMS",
    manifest_extra = """
    <uses-permission android:name="android.permission.RECEIVE_SMS" />
    <uses-permission android:name="android.permission.READ_SMS" />
    """,
    package = "com.android.tools.e2etests.sms",
    deps = [
        "//deps/proto:aemu_java_grpc_lite",
        "//ets/java/com/android/tools/e2etests/grpc:grpc_lib",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_runner",
        "@tradefed//:tradefed_jars",
    ],
)
