load("//ets:ets.bzl", "ets_device_test", "ets_pkg")

ets_pkg(
    name = "pkg",
    srcs = [
        ":BootTest.apk",
        ":BootTest_config",
    ],
)

ets_device_test(
    name = "BootTest",
    srcs = ["BootTest.kt"],
    description = "Tests related to the emulator boot",
    package = "com.android.tools.e2etests.boot",
    deps = [
        "//deps/proto:aemu_java_grpc_lite",
        "//ets/java/com/android/tools/e2etests/grpc:grpc_lib",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_runner",
        "@tradefed//:tradefed_jars",
    ],
)
